# Generated by Django 4.2.11 on 2026-03-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_date_scanned_alter_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
