# Generated by Django 4.2.11 on 2026-03-09 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcollection',
            name='cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.card'),
        ),
    ]
