# Generated by Django 4.2.11 on 2026-03-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardcollection_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcollection',
            name='cards',
        ),
        migrations.AddField(
            model_name='cardcollection',
            name='cards',
            field=models.ManyToManyField(null=True, to='cards.card'),
        ),
    ]
