# Generated by Django 4.2.11 on 2026-03-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_cardcollection_cards_cardcollection_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcollection',
            name='cards',
            field=models.ManyToManyField(to='cards.card'),
        ),
    ]
