# Generated by Django 4.2.11 on 2026-03-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_cardcollection_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_scanned',
            field=models.DateField(auto_created=True),
        ),
    ]
