# Generated by Django 4.2.11 on 2026-03-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_date_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_scanned',
            field=models.DateField(auto_now_add=True),
        ),
    ]
