# Generated by Django 4.2.11 on 2026-03-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='scanned_at',
            new_name='date_scanned',
        ),
        migrations.AddField(
            model_name='card',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='set_name',
            field=models.CharField(blank=True, default='Unknown Set', max_length=100),
        ),
    ]
