# Generated by Django 4.2.28 on 2026-03-05 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.movie'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.seat'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('movie', 'seat_number'), name='unique_seat_per_movie'),
        ),
    ]
