# Generated by Django 4.2.11 on 2026-03-10 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('card_set', models.CharField(blank=True, default='', max_length=200)),
                ('card_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_tier', models.CharField(choices=[('ungraded', 'Ungraded'), ('psa_1', 'PSA 1'), ('psa_2', 'PSA 2'), ('psa_3', 'PSA 3'), ('psa_4', 'PSA 4'), ('psa_5', 'PSA 5'), ('psa_6', 'PSA 6'), ('psa_7', 'PSA 7'), ('psa_8', 'PSA 8'), ('psa_9', 'PSA 9'), ('psa_10', 'PSA 10')], default='ungraded', max_length=10)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('submitted', 'Submitted for Grading'), ('graded', 'Graded'), ('sold', 'Sold')], default='watching', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_trend', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
