# Generated by Django 4.2.11 on 2026-03-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedcard',
            name='user',
        ),
    ]
