# Generated by Django 4.2.11 on 2026-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_valuesnapshot_alter_trackedcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedcard',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackedcard',
            name='status',
            field=models.CharField(choices=[('owned', 'Owned'), ('watching', 'Watching'), ('submitted', 'Submitted for Grading'), ('graded', 'Graded'), ('sold', 'Sold')], default='watching', max_length=20),
        ),
    ]
