# Generated by Django 4.2.28 on 2026-03-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_seat_is_booked_seat_movie_alter_booking_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
